FROM python:3-slim
RUN mkdir /code
WORKDIR /code
ADD . /code/
RUN pip install -r requirements.txt
LABEL Maintainer = Bartlomiej Paluch
ENV SOURCE = http://uploader:8999
ENV KAFKA_HOST = kafka:9092
ENV PG_USER = postgres
ENV PG_PASS = qwe123
ENV PG_HOST = localhost
ENV PG_PORT = 5432

RUN pip install -r requirements.txt
CMD ["python", "manage.py", "makemigrations"]
CMD ["python", "manage.py", "migrate"]
CMD ["python", "manage.py", "runserver", "8999"]