server:
  port: ${UPLOADER_PORT:8999}

spring:
  cloud:
    stream:
      function:
        definition: fileCreated
      bindings:
        fileSaved-out-0:
          destination: 'fileSaved'
          contentType: application/json
        fileCreated-out-0:
          destination: 'fileCreated'
          contentType: application/json
        fileCreated-in-0:
          contentType: application/json
          destination: 'fileSaved'
      kafka:
        binder:
          brokers: ${BROKER_IP:localhost}:${BROKER_PORT:9092}
          auto-create-topics: true
          configuration:
            auto.offset.reset: latest
  sql:
    init:
      mode: always
      platform: postgres
  jpa:
    hibernate:
      ddl-auto: create

spring.main.banner-mode: off
logging.level.org.springframework: ERROR

spring.datasource.url: jdbc:postgresql://${POSTGRES_IP:localhost}:${POSTGRES_PORT:5432}/${UPLOADER_DB:projectdb}
spring.datasource.username: ${UPLOADER_USERNAME:psql}
spring.datasource.password: ${UPLOADER_PASSWORD:postgres}

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.servlet.multipart.max-file-size: 2MB
spring.servlet.multipart.max-request-size: 2MB
server.error.include-stacktrace: always