CREATE USER docker WITH PASSWORD 'qwe123';
CREATE DATABASE blog;
GRANT ALL PRIVILEGES ON DATABASE blog TO docker;
CREATE DATABASE uploader;
GRANT ALL PRIVILEGES ON DATABASE uploader TO docker;
CREATE DATABASE logdb;
GRANT ALL PRIVILEGES ON DATABASE logdb TO docker;